name: wecode_2021
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  device_info: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.3.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.1

  image_picker: ^0.8.4+4
  provider: ^6.0.2
  url_launcher: ^6.0.18
  flutter_native_timezone: ^2.0.0
  http: ^0.13.4
  image: ^3.0.8
  path_provider: ^2.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.1
  sqflite: ^2.0.2
  synchronized: ^3.0.0
  sqlbrite: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - image/
  #  - sound/
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
